# Generated by Django 5.1.4 on 2025-01-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.CharField(max_length=200),
        ),
    ]
