# Generated by Django 5.1.4 on 2025-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0002_album_alter_cancion_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCancion', models.IntegerField()),
                ('idAlbum', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
    ]
