# Generated by Django 5.1.4 on 2025-01-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0002_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='idgenero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdSpotify.genero'),
        ),
    ]
