# Generated by Django 5.1.4 on 2025-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0003_temporal_rename_titulo_album_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='listasCanciones', to='bdSpotify.cancion'),
        ),
    ]
