# Generated by Django 5.1.4 on 2025-01-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0003_cancion_idgenero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='genero',
        ),
    ]
