# Generated by Django 5.1.4 on 2025-01-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0004_remove_cancion_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones_genero', to='bdSpotify.genero'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='idgenero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones_idgenero', to='bdSpotify.genero'),
        ),
    ]
