# Generated by Django 5.1.4 on 2025-01-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0004_alter_lista_canciones'),
    ]

    operations = [

    ]
