# Generated by Django 5.1.4 on 2025-01-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0005_cancion_genero_alter_cancion_idgenero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='idgenero',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdSpotify.genero'),
        ),
    ]
