# Generated by Django 5.1.4 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0005_alter_cancion_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='listas', to='bdSpotify.cancion'),
        ),
    ]
