# Generated by Django 5.1.4 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0006_alter_lista_canciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.CharField(max_length=200),
        ),
    ]
