# Generated by Django 5.1.4 on 2025-01-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0007_alter_cancion_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temporal',
        ),
    ]
