# Generated by Django 5.1.4 on 2025-01-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0008_delete_temporal'),
    ]

    operations = [

    ]
