# Generated by Django 5.1.4 on 2025-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0009_alter_cancion_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.CharField(max_length=200),
        ),
    ]
