# Generated by Django 5.1.4 on 2025-01-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0011_cancion_albumf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='albumF',
            new_name='albumf',
        ),
    ]
