# Generated by Django 5.1.4 on 2025-01-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0013_temporal_remove_cancion_albumf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='albumf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='bdSpotify.album'),
        ),
    ]
