# Generated by Django 5.1.4 on 2025-01-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0006_remove_cancion_idgenero_alter_cancion_genero'),
        ('bdSpotify', '0014_cancion_albumf'),
    ]

    operations = [
    ]
